name: Build IPA
on: workflow_dispatch
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: bash ipabuild_fixed.sh
    - uses: actions/upload-artifact@v4
      with:
        name: dirtyZero-ipa
        path: dirtyZero.ipa
